from __future__ import annotations

import os
import smtplib
from datetime import datetime, timedelta, timezone
from email.message import EmailMessage
from typing import Any, Tuple

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
from requests.exceptions import RequestException

from ml import PrometheusClient, explain_anomalies, IsolationForestDetector, RollingMeanDetector, EWMAAnomalyDetector, ZScoreDetector
from ml.feature_engineering import add_rolling_features

PROMETHEUS_URL = os.getenv('PROMETHEUS_URL', 'http://localhost:9090')
METRIC_OPTIONS: dict[str, str] = {
    'CPU utilization (%)': '100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)',
    'Load 1m': 'node_load1',
    'Memory available (bytes)': 'node_memory_MemAvailable_bytes',
    'CPU total counter (debug)': 'node_cpu_seconds_total',
}

SMTP_SERVER = os.getenv('EMAIL_SMTP_SERVER', 'smtp.gmail.com')
SMTP_PORT = int(os.getenv('EMAIL_SMTP_PORT', '587'))
SMTP_USER = os.getenv('EMAIL_USER')
SMTP_PASSWORD = os.getenv('EMAIL_PASSWORD')
ALERT_EMAIL_TO = [addr.strip() for addr in os.getenv('ALERT_EMAIL_TO', '').split(',') if addr.strip()]
ALERT_EMAIL_FROM = os.getenv('ALERT_EMAIL_FROM', SMTP_USER)

# Small UI styles
_STYLES = """
<style>
    .card {border-radius:8px; padding:12px; margin-bottom:12px; background:#f7f9fb}
    .metric-title {font-weight:600}
</style>
"""


def get_prometheus_instances(prometheus_url: str) -> list[str]:
    client = PrometheusClient(prometheus_url)
    try:
        df = client.query('up')
    except RequestException:
        return []

    if df.empty:
        return []

    return sorted(df['instance'].dropna().unique().tolist())


def load_metrics(metric_query: str, prometheus_url: str, hours: int) -> pd.DataFrame:
    client = PrometheusClient(prometheus_url)
    now = pd.Timestamp.now(tz='UTC')
    start = now - pd.Timedelta(hours=hours)
    df = client.query_range(query=metric_query, start=start.isoformat(), end=now.isoformat(), step='30s')
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='s', utc=True)
    return df


def filter_instances(df: pd.DataFrame, instance: str) -> pd.DataFrame:
    if instance == 'All nodes':
        return df
    return df[df['instance'] == instance].reset_index(drop=True)


def email_alerts_configured() -> bool:
    return bool(SMTP_USER and SMTP_PASSWORD and ALERT_EMAIL_TO and ALERT_EMAIL_FROM)


def init_alert_session_state() -> None:
    st.session_state.setdefault('email_alert_history', {})
    st.session_state.setdefault('email_alert_errors', [])


def should_send_email_alert(instance: str, severity: str) -> bool:
    key = f'{instance}|{severity}'
    history = st.session_state['email_alert_history']
    last_sent = history.get(key)
    if last_sent is None:
        return True
    return datetime.now(timezone.utc) - last_sent >= timedelta(minutes=30)


def record_email_alert_sent(instance: str, severity: str) -> None:
    key = f'{instance}|{severity}'
    st.session_state['email_alert_history'][key] = datetime.now(timezone.utc)


def clear_email_alert_history(instance: str) -> None:
    history = st.session_state['email_alert_history']
    for key in list(history.keys()):
        if key.startswith(f'{instance}|'):
            history.pop(key, None)


def send_alert_email(instance: str, severity: str, peak_value: float | None, current_value: float | None) -> Tuple[bool, str | None]:
    if not email_alerts_configured():
        return False, 'Email alerting is not configured.'

    recipients = ALERT_EMAIL_TO
    body = [
        f'ONGC AI Monitoring Alert for {instance}',
        f'Severity: {severity}',
        f'Peak CPU: {peak_value:.2f}%' if peak_value is not None else 'Peak CPU: unknown',
        f'Current CPU: {current_value:.2f}%' if current_value is not None else 'Current CPU: unknown',
        f'Prometheus: {PROMETHEUS_URL}',
        '',
        'This alert was generated by the streamlit monitoring dashboard.',
    ]
    message = EmailMessage()
    message['From'] = ALERT_EMAIL_FROM
    message['To'] = ', '.join(recipients)
    message['Subject'] = f'[ONGC AI Monitoring] {instance} Critical Severity'
    message.set_content('\n'.join(body))

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as smtp:
            smtp.starttls()
            smtp.login(SMTP_USER, SMTP_PASSWORD)
            smtp.send_message(message)
        return True, None
    except Exception as exc:
        return False, str(exc)


def render_header() -> None:
    st.set_page_config(page_title='ONGC AI Monitoring', layout='wide')
    st.title('ONGC AI Monitoring')
    st.markdown('A machine intelligence layer that complements Grafana for anomaly detection.')


def render_sidebar(instances: list[str]) -> tuple[str, str, int, str, bool]:
    st.sidebar.header('AI Dashboard')
    prometheus_url = st.sidebar.text_input('Prometheus URL', PROMETHEUS_URL, key='prometheus_url')
    if instances:
        instance = st.sidebar.selectbox('Node instance', ['All nodes'] + instances, key='node_instance')
    else:
        st.sidebar.markdown('No instances discovered from Prometheus. Enter a valid instance label manually.')
        instance = st.sidebar.text_input('Node instance', '192.168.56.101:9100', key='node_instance_manual')

    metric = st.sidebar.selectbox('Metric', list(METRIC_OPTIONS.keys()), index=0, key='metric')
    hours = st.sidebar.slider('Lookback hours', 1, 24, 3, key='hours')
    auto_refresh = st.sidebar.checkbox('Auto-refresh every 30s', value=False, key='auto_refresh')
    return instance, metric, hours, prometheus_url, auto_refresh


def run_detectors(df: pd.DataFrame, metric_name: str, instance: str = None) -> dict[str, Any]:
    # If analyzing all nodes, run detectors per-instance and aggregate
    if instance == 'All nodes' and 'instance' in df.columns:
        unique_instances = df['instance'].unique()
        all_results: dict[str, Any] = {}
        
        for inst in unique_instances:
            inst_df = df[df['instance'] == inst].reset_index(drop=True)
            if inst_df.empty:
                continue
            inst_results = run_detectors(inst_df, metric_name, instance=None)
            all_results[str(inst)] = inst_results
        
        return all_results
    
    detectors = {
        'Rolling Mean': RollingMeanDetector(metric=metric_name),
        'EWMA': EWMAAnomalyDetector(metric=metric_name),
        'Z Score': ZScoreDetector(metric=metric_name),
        'Isolation Forest': IsolationForestDetector(metric=metric_name),
    }
    results: dict[str, Any] = {}

    for name, detector in detectors.items():
        try:
            if hasattr(detector, 'fit') and name in ['Z Score', 'Isolation Forest']:
                detector.fit(df)
            anomalies = detector.predict(df)
            results[name] = {
                'summary': detector.explain(df),
                'anomalies': explain_anomalies(anomalies),
                'score': detector.score(df),
            }
        except Exception as exc:
            results[name] = {'error': str(exc)}

    return results


def summarize_recent_incidents(anomalies_df: pd.DataFrame) -> dict[str, Any]:
    if anomalies_df.empty:
        return {
            'incident_count': 0,
            'affected_nodes': 0,
            'last_anomaly': None,
            'has_incidents': False,
        }

    incidents: list[dict[str, Any]] = []
    for instance, group in anomalies_df.groupby('instance'):
        sorted_group = group.sort_values('timestamp').reset_index(drop=True)
        sorted_group['timestamp'] = pd.to_datetime(sorted_group['timestamp'], utc=True)
        current_start = sorted_group.loc[0, 'timestamp']
        current_end = current_start
        for idx in range(1, len(sorted_group)):
            ts = sorted_group.loc[idx, 'timestamp']
            if isinstance(ts, pd.Timestamp) and isinstance(current_end, pd.Timestamp) and ts - current_end <= pd.Timedelta(minutes=1.5):
                current_end = ts
            else:
                incidents.append({'instance': instance, 'start': current_start, 'end': current_end})
                current_start = ts
                current_end = ts
        incidents.append({'instance': instance, 'start': current_start, 'end': current_end})

    last_anomaly = max(item['end'] for item in incidents)
    return {
        'incident_count': len(incidents),
        'affected_nodes': len({item['instance'] for item in incidents}),
        'last_anomaly': last_anomaly,
        'has_incidents': len(incidents) > 0,
    }


def render_summary(df: pd.DataFrame, metric_name: str, results: dict[str, Any], anomalies_df: pd.DataFrame) -> None:
    st.markdown(_STYLES, unsafe_allow_html=True)
    instances = sorted(df['instance'].unique().tolist())
    latest = df.sort_values('timestamp').groupby('instance').tail(1)
    avg_value = float(df['value'].mean()) if not df.empty else 0.0
    anomaly_scores = [r['score'] for r in results.values() if 'score' in r]
    overall_score = float(sum(anomaly_scores) / len(anomaly_scores)) if anomaly_scores else 0.0
    
    # Check for critical instances by analyzing anomalies
    critical_count = 0
    if not anomalies_df.empty and 'instance' in anomalies_df.columns:
        critical_count = len(anomalies_df['instance'].unique())
    
    # Determine status: if any Critical anomalies detected, show Alert; otherwise use score-based logic
    if critical_count > 0:
        status = 'Alert' if critical_count >= len(instances) / 2 else 'Warning'
    else:
        status = 'Healthy' if overall_score < 0.3 else 'Warning' if overall_score < 0.7 else 'Alert'
    incident_summary = summarize_recent_incidents(anomalies_df)
    history_line = (
        f"Last 1h: {incident_summary['incident_count']} incident(s), affected {incident_summary['affected_nodes']} node(s), last at {incident_summary['last_anomaly'].strftime('%Y-%m-%d %H:%M')}"
        if incident_summary['has_incidents']
        else 'Last 1h: No incidents detected.'
    )

    # Summary cards
    col1, col2, col3, col4 = st.columns([2,1,1,1])
    with col1:
        st.markdown(
            f"<div class='card'><div class='metric-title'>Cluster status</div><h3>{status}</h3><div>AI anomaly score: <b>{overall_score:.2f}</b></div><div>{history_line}</div></div>",
            unsafe_allow_html=True,
        )
    col2.metric('Nodes monitored', len(instances))
    col3.metric('Metric', metric_name)
    col4.metric('Average value', f'{avg_value:.2f}')

    with st.expander('Latest node values'):
        st.dataframe(latest[['instance', 'metric_name', 'value', 'timestamp']].reset_index(drop=True))

    st.markdown('---')

    # Per-node health cards (show latest metric per node)
    st.markdown('**Per-node summary**')
    node_cols = st.columns(len(instances) if len(instances) <= 4 else 4)
    idx = 0
    latest_by_instance = latest.set_index('instance') if not latest.empty else None
    for inst in instances:
        col = node_cols[idx % len(node_cols)]
        with col:
            if latest_by_instance is not None and inst in latest_by_instance.index:
                row = latest_by_instance.loc[inst]
                val = float(row['value'])
                st.markdown(f"**{inst}**")
                st.metric('Value', f"{val:.2f}")
            else:
                st.markdown(f"**{inst}**")
                st.write('No data')
        idx += 1
    st.markdown('---')


def compute_consensus_severity(confidence: float, peak_value: float | None) -> str:
    if peak_value is not None and peak_value < 30:
        return 'Low'
    if confidence > 0.75:
        return 'Critical'
    if confidence > 0.5:
        return 'High'
    if confidence > 0.25:
        return 'Medium'
    return 'Low'


def render_auto_refresh(auto_refresh: bool) -> None:
    if auto_refresh:
        st.markdown('<meta http-equiv="refresh" content="30">', unsafe_allow_html=True)


def current_value_status(current_value: float) -> str:
    if current_value >= 90:
        return 'Critical'
    if current_value >= 70:
        return 'High'
    if current_value >= 50:
        return 'Medium'
    if current_value >= 30:
        return 'Low'
    return 'Normal'


def render_consensus(results: dict[str, Any], latest_values: dict[str, float]) -> None:
    # Build consensus across models per instance
    st.markdown('### ML Consensus')
    st.markdown('_Severity reflects the peak CPU value observed within the selected lookback window, not the current live value._')
    # collect anomalies per model per instance
    per_instance_votes: dict[str, list[str]] = {}
    per_instance_values: dict[str, list[float]] = {}
    for model_name, info in results.items():
        anomalies = info.get('anomalies', []) if isinstance(info, dict) else []
        for a in anomalies:
            inst = a.get('instance', 'unknown')
            per_instance_votes.setdefault(inst, []).append(model_name)
            value = None
            if isinstance(a.get('details'), dict):
                value = a['details'].get('value')
            if value is None:
                value = a.get('value')
            if isinstance(value, (int, float)):
                per_instance_values.setdefault(inst, []).append(float(value))

    if not per_instance_votes:
        st.write('No anomalies detected by any model.')
        return

    for inst, voters in per_instance_votes.items():
        total_models = len(results)
        votes = len(set(voters))
        confidence = votes / total_models
        peak_value = max(per_instance_values.get(inst, [])) if per_instance_values.get(inst) else None
        current_value = latest_values.get(inst)
        severity = compute_consensus_severity(confidence, peak_value)
        pct = int(confidence * 100)

        header = f"**{inst}** — Severity: **{severity}**"
        if peak_value is not None and current_value is not None:
            header += f" (peak {peak_value:.0f}%, current {current_value:.0f}%)"
        elif peak_value is not None:
            header += f" (peak {peak_value:.0f}%)"
        elif current_value is not None:
            header += f" (current {current_value:.0f}%)"
        st.markdown(header)

        if current_value is not None:
            current_status = current_value_status(current_value)
            st.markdown(f"Current status: **{current_status}** — {current_value:.2f}%")

        # visual confidence
        st.progress(confidence)
        if peak_value is not None:
            st.markdown(f"Peak CPU observed: {peak_value:.2f}%")
        if severity == 'Critical' and should_send_email_alert(inst, severity):
            success, error = send_alert_email(inst, severity, peak_value, current_value)
            if success:
                record_email_alert_sent(inst, severity)
                st.success(f'Email alert sent for {inst} (Critical).')
            else:
                st.error(f'Failed to send email alert for {inst}: {error}')
                st.session_state['email_alert_errors'].append(f'{inst}: {error}')
        if severity == 'Low' and peak_value is not None and peak_value < 30:
            st.info('Severity is set to Low because the detected peak CPU is below 30%, even though models agreed on an anomaly.')
        st.markdown(f"Confidence: {pct}% — Models: {', '.join(sorted(set(voters)))}")


def render_chart(df: pd.DataFrame, metric_name: str, anomalies: pd.DataFrame | None = None) -> None:
    if df.empty:
        st.warning('No data to chart.')
        return

    fig = px.line(df, x='timestamp', y='value', color='instance', title=f'{metric_name} over time')
    fig.update_layout(legend_title_text='Instance')
    if anomalies is not None and not anomalies.empty:
        try:
            scatter = go.Scatter(
                x=anomalies['timestamp'],
                y=anomalies['value'],
                mode='markers',
                marker=dict(color='red', size=8),
                name='Anomalies',
            )
            fig.add_trace(scatter)
        except Exception:
            pass
    st.plotly_chart(fig, use_container_width=True)


def render_ml_insights(results: dict[str, Any]) -> None:
    st.markdown('### ML model insights')
    for name, info in results.items():
        if 'error' in info:
            st.error(f'{name}: {info["error"]}')
            continue
        score = info.get('score', 0.0)
        summary = info.get('summary', {})
        anomalies = info.get('anomalies', [])
        with st.expander(f"{name} — score {score:.2f} ({len(anomalies)} anomalies)"):
            st.write('Summary:')
            st.json(summary)
            if anomalies:
                st.write('Recent anomalies:')
                st.table(pd.DataFrame(anomalies).tail(5))
            # suggestions
            if score > 0.7:
                st.warning('High anomaly score — investigate processes, CPU-bound tasks, or memory leaks.')
            elif score > 0.3:
                st.info('Moderate anomalies — keep monitoring and review trends.')
            else:
                st.success('No significant anomalies detected by this model.')
            st.write('Recommended action:')
            st.markdown('- Check top CPU processes: `top` / `ps aux --sort=-%cpu`')
            st.markdown('- Verify container limits or runaway jobs')
            st.write('---')


def main() -> None:
    render_header()
    instances = get_prometheus_instances(PROMETHEUS_URL)
    instance, selected_metric, hours, prometheus_url, auto_refresh = render_sidebar(instances)
    render_auto_refresh(auto_refresh)
    metric_query = METRIC_OPTIONS[selected_metric]

    try:
        df = load_metrics(metric_query, prometheus_url, hours)
    except RequestException as exc:
        st.error(f'Cannot connect to Prometheus at {prometheus_url}: {exc}')
        return
    except Exception as exc:
        st.error(str(exc))
        return

    if df.empty:
        st.warning('No metrics returned from Prometheus. Verify instance and metric names.')
        return

    df = filter_instances(df, instance)
    if df.empty:
        st.warning('No data returned for the selected instance. Try All nodes or another instance.')
        return

    init_alert_session_state()
    df = add_rolling_features(df)
    results = run_detectors(df, selected_metric, instance)
    
    # Normalize results structure: if per-instance, convert to model-centric format
    if instance == 'All nodes' and 'instance' in df.columns and isinstance(results, dict):
        # Check if results is per-instance (first key is an instance name, value is dict of models)
        first_value = next(iter(results.values())) if results else None
        if isinstance(first_value, dict) and 'Rolling Mean' in first_value:
            # Per-instance format - convert to model-centric
            model_centric_results: dict[str, Any] = {
                'Rolling Mean': {'anomalies': [], 'summary': {}, 'score': 0.0},
                'EWMA': {'anomalies': [], 'summary': {}, 'score': 0.0},
                'Z Score': {'anomalies': [], 'summary': {}, 'score': 0.0},
                'Isolation Forest': {'anomalies': [], 'summary': {}, 'score': 0.0},
            }
            for inst_name, inst_models in results.items():
                for model_name, model_data in inst_models.items():
                    if isinstance(model_data, dict) and 'anomalies' in model_data:
                        model_centric_results[model_name]['anomalies'].extend(model_data['anomalies'])
                        model_centric_results[model_name]['summary'] = model_data.get('summary', {})
                        # Use MAX score across instances (any anomaly in any instance should be reported)
                        current_score = model_data.get('score', 0.0)
                        model_centric_results[model_name]['score'] = max(model_centric_results[model_name]['score'], current_score)
            results = model_centric_results

    latest_values = (
        df.sort_values('timestamp')
          .groupby('instance')
          .tail(1)
          .set_index('instance')['value']
          .astype(float)
          .rename_axis('instance')
          .reset_index()
    )
    latest_values = {str(row['instance']): float(row['value']) for _, row in latest_values.iterrows()}

    # aggregate anomalies across models for chart highlighting
    anomalies_list: list[dict] = []
    for info in results.values():
        if isinstance(info, dict) and 'anomalies' in info and info['anomalies']:
            anomalies_list.extend(info['anomalies'])
    anomalies_df = pd.DataFrame(anomalies_list) if anomalies_list else pd.DataFrame()
    if not anomalies_df.empty and 'timestamp' in anomalies_df.columns:
        anomalies_df['timestamp'] = pd.to_datetime(anomalies_df['timestamp'], utc=True)

    render_summary(df, selected_metric, results, anomalies_df)
    render_consensus(results, latest_values)
    render_chart(df, selected_metric, anomalies=anomalies_df)
    render_ml_insights(results)


if __name__ == '__main__':
    main()
