FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc g++ make zlib1g-dev libjpeg-dev libfreetype6-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt

COPY . /app

ENV PYTHONPATH=/app

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "streamlit_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
