- labels:
    job: node_exporter
  targets:
    # Replace these example values with the IP addresses or hostnames of your own node_exporter targets.
    - '192.168.56.101:9100'
    - '192.168.56.102:9100'
    - '192.168.56.103:9100'